- name: Debugger JavaScript Exists?
  stat:
    path: "$HOME/.local/share/vscode-node-debug2"
  register: node_debugger
  tags:
    - install
    - debugger

- name: Debugger - JavaScript
  ansible.builtin.git:
    repo: 'git@github.com:microsoft/vscode-node-debug2.git'
    dest: "$HOME/.local/share/vscode-node-debug2"
  tags:
    - install
    - debugger
  when: node_debugger.stat.exists == False

- name: Debugger npm i and build JavaScript
  shell: cd $HOME/.local/share/vscode-node-debug2 && npm i && npm run build
  tags:
    - install
    - debugger

- name: Debugger netcoredbg Exists?
  stat:
    path: "$HOME/.local/share/netcoredbg/netcoredbg"
  register: netcoredbg_debugger
  tags:
    - install
    - debugger

- name: create folders netcoredbg
  shell: mkdir -p $HOME/.local/share/netcoredbg
  tags:
    - install
    - debugger
    - netcoredbg

- name: download netcoredbg
  shell: cd $HOME/.local/share/netcoredbg && wget https://github.com/Samsung/netcoredbg/releases/download/2.0.0-915/netcoredbg-linux-amd64.tar.gz
  tags:
    - install
    - debugger
    - netcoredbg 
  when: netcoredbg_debugger.stat.exists == False

- name: extract netcoredbg
  shell: cd $HOME/.local/share/netcoredbg && tar -xzvf netcoredbg-linux-amd64.tar.gz
  tags:
    - install
    - debugger
    - netcoredbg 
  when: netcoredbg_debugger.stat.exists == False
