- name: Get Microsoft trusted key
  shell: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  tags:
  - install
  - dotnet

- name: Install Microsoft trusted key
  become: true
  shell: dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb
  tags:
  - install
  - dotnet

- name: Install transport
  become: true
  apt:
    name: ["apt-transport-https"]
    update_cache: yes
  tags:
    - install
    - dotnet

- name: Install dotnet
  become: true
  apt:
    name: ["dotnet-sdk-6.0"]
    update_cache: yes
  tags:
    - install
    - dotnet

- name: Install gnupg and ca-certificates
  become: true
  apt:
    name: ["gnupg", "ca-certificates"]
    update_cache: yes
  tags:
    - install
    - mono

- name: Install uncrustify
  become: true
  apt:
    name: ["uncrustify"]
    update_cache: yes
  tags:
    - install
    - dotnet

- name: Install artifact credential provider
  shell: sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)"
  tags:
  - install
  - dotnet
  - nuget
