- name: Get Microsoft trusted key
  shell: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  tags:
  - install
  - dotnet

- name: Install Microsoft trusted key
  become: true
  shell: dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb
  tags:
  - install
  - dotnet

- name: Install transport
  become: true
  apt:
    name: ["apt-transport-https"]
    update_cache: yes
  tags:
    - install
    - dotnet

- name: Install dotnet
  become: true
  apt:
    name: ["dotnet-sdk-6.0"]
    update_cache: yes
  tags:
    - install
    - dotnet

- name: Install gnupg and ca-certificates
  become: true
  apt:
    name: ["gnupg", "ca-certificates"]
    update_cache: yes
  tags:
    - install
    - mono

- name: Add an apt key by id from a keyserver
  become: true
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  tags:
    - install
    - mono

- name: Add source
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.mono-project.com/repo/ubuntu stable-focal main
  tags:
  - install
  - mono

- name: Install mono
  become: true
  apt:
    name: ["mono-devel"]
    update_cache: yes
  tags:
    - install
    - mono
