- name: download dotnet tools
  shell: wget -P {{ lookup('env', 'HOME') }}/.local/bin https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
  tags:
  - install
  - dotnet
  - dotnet-tools

- name: install latest dotnet
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.local/bin/dotnet-install.sh"
  tags:
  - install
  - dotnet
  - dotnet-tools

- name: install latest dotnet
  script:
    cmd: "{{ lookup('env', 'HOME') }}/.local/bin/dotnet-install.sh -v 3.1.424"
  tags:
  - install
  - dotnet
  - dotnet-tools

- name: Install gnupg and ca-certificates
  become: true
  apt:
    name: ["gnupg", "ca-certificates"]
    update_cache: yes
  tags:
    - install
    - mono

- name: Install artifact credential provider
  shell: sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)"
  tags:
  - install
  - dotnet
  - nuget
