- name: Install dotnet
  become: true
  apt:
    name: ["dotnet6"]
    update_cache: yes
  tags:
    - install
    - dotnet

- name: Install gnupg and ca-certificates
  become: true
  apt:
    name: ["gnupg", "ca-certificates"]
    update_cache: yes
  tags:
    - install
    - mono

- name: Install artifact credential provider
  shell: sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)"
  tags:
  - install
  - dotnet
  - nuget
